### ISSUE TITLE
Problem working on Android (Unity 4.6.3)

### ISSUE THREAD

**Issue by ArthurBn** [jderrough/UnitySlippyMap#11]
Hello, I'm working on Unity 4.6.3, on an Android application.

The map work fine in Unity (in editor), but not in Android. 
By not working I mean that I can see the buttons but I don't see any map tiles.
The DebugLogs are telling me that everything is working : 

(TestMap.cs )

Debug.Log("DEBUG: file doesn't exist: " + newfilepath);
Debug.Log("DEBUG: will write: '" + filepath + "' to: '" + newfilepath + "'");
Debug.Log("DEBUG: exists: " + newfilepath);
Debug.Log("DEBUG: using MBTiles file: " + filepath);

All these messages are showing, so it should work correctly but nothing is showing on Android.

So if you know what the problem can be, please let me know =).

And thanks in advance for your answers.

**Comment by creatio-ua** [comment]
Hi!
I had similar problems when my device had issues with Internet connection.

**Comment by ArthurBn** [comment]
The thing is, my device don't have internet problems, and I just tried on another device, but I get the same problem. (Samsung Galaxy Tab 2 and Tab S).
