### ISSUE TITLE
Can't input coordinates above longtitude 100.

### ISSUE THREAD

**Issue by Smileynator** [jderrough/UnitySlippyMap#12]
If i input a long above 90, i will get the following warning:
ArgumentException: Transformation cannot be computed at the poles.
 at Map.CenterWGS84: double[] newCenterESPG900913 = wgs84ToEPSG900913Transform.Transform (value);
If i try to enter something like singapore (long at 103 or something like that), as the starting center. The code will simply freeze unity.

Any reason for this issue and any idea how to fix it?

**Comment by jderrough** [comment]
I think you might pass the latitude as longitude and vice versa. Please try passing the longitude first.
For Singapore:
`map.CenterWGS84 = new double[2] { 103.8, 1.3 };`

Let me know if that solves it for you so I might close the issue.
