### ISSUE TITLE
Zooming out to minimum zoom (3) and then to maximum (18) causes fatal error.

### ISSUE THREAD

**Issue by pixelfat** [jderrough/UnitySlippyMap#13]
Zooming to minimum and then maximum zoom extents using 's' and 'z' seems to always result in a fatal error. The same error seems to occur sometimes when quickly navigating around high zoom levels.

I'm using Unity 5.1.0f3,

**Comment by jderrough** [comment]
Hi @pixelfat,

Do you have infos on that issue, please? For example, on what platform your code is running, or the stack trace of the crash, ...
