### ISSUE TITLE
OSM zoom issue

### ISSUE THREAD

**Issue by cassiss** [jderrough/UnitySlippyMap#15]
Hello,

I have encountered some issues when usig OSM map tiles. If I zoom out farther than 6 on the map, all the tiles are just grey. The material seems to have no texture loaded.

Do you have any idea what could be the reason for this or how I could get it to work for lower zoom levels?

**Comment by jderrough** [comment]
Hi Sarah,

Does the tile provider you are using support that zoom level? Have you
tested fetching tiles outside of Unity and UnitySlippyMap (e.g in a web
browser)?

On Wed, Mar 9, 2016 at 3:26 PM Sarah <notifications@github.com> wrote:

> Hello,
>
> I have encountered some issues when usig OSM map tiles. If I zoom out
> farther than 6 on the map, all the tiles are just grey. The material seems
> to have no texture loaded.
>
> Do you have any idea what could be the reason for this or how I could get
> it to work for lower zoom levels?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jderrough/UnitySlippyMap/issues/15>.
>
-- 

Jonathan Derrough
+33 (0) 6 84 74 76 03
jonathan.derrough@gmail.com

**Comment by cassiss** [comment]
Hello Jonathan,

thank you for the quick reply.
Yes I tested it in the webbrowser, and it works fine, the zoom levels should be supported up until 1.
I tried debugging in Unity to take a look at the sent request (at OSMTileLayerBehavior GetTileURL) and it never seems to send any requests at all for zooms lower than 6. No error messages or warnings though, so I don't know where it could fail.

Kind Regards,

Sarah

**Comment by jderrough** [comment]
Sarah,

You can add #define DEBUG_LOG at the very beginning of MapBehaviour.cs to
get more details about what is going on. Other than that, I would suggest
using a step debugger to get more in depth.

Best regards,
Jonathan

On Wed, Mar 9, 2016 at 3:58 PM Sarah <notifications@github.com> wrote:

> Hello Jonathan,
>
> thank you for the quick reply.
> Yes I tested it in the webbrowser, and it works fine, the zoom levels
> should be supported up until 1.
> I tried debugging in Unity to take a look at the sent request (at
> OSMTileLayerBehavior GetTileURL) and it never seems to send any requests at
> all for zooms lower than 6. No error messages or warnings though, so I
> don't know where it could fail.
>
> Kind Regards,
>
> Sarah
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jderrough/UnitySlippyMap/issues/15#issuecomment-194333485>
> .
>
-- 

Jonathan Derrough
+33 (0) 6 84 74 76 03
jonathan.derrough@gmail.com

**Comment by cassiss** [comment]
Hello and thanks again,
I found the issue while debugging, the tiles were simply outside the camera frustum. Because of TestPlanesAABB in GrowTiles they just stopped sending requests too, so I didn't think of checking my camera. Setting a higher value for the far clipping plane solved my problem, I can zoom out all the way to 3 now.

Kind Regards,
Sarah

**Comment by akiszelewski** [comment]
Please take me off this chain.

**Comment by jderrough** [comment]
akiszelewski,

You'll have to unsubscribe to issues tracking on Github, I can't do it for
you.

On Wed, Mar 9, 2016 at 5:16 PM akiszelewski <notifications@github.com>
wrote:

> Please take me off this chain.
> On Mar 9, 2016 08:15, "Sarah" <notifications@github.com> wrote:
>
> > Hello and thanks again,
> > I found the issue while debugging, the tiles were simply outside the
> > camera frustum. Because of TestPlanesAABB in GrowTiles they just stopped
> > sending requests too, so I didn't think of checking my camera. Setting a
> > higher value for the far clipping plane solved my problem, I can zoom out
> > all the way to 3 now.
> >
> > Kind Regards,
> > Sarah
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jderrough/UnitySlippyMap/issues/15#issuecomment-194370593
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jderrough/UnitySlippyMap/issues/15#issuecomment-194371066>
> .
>
-- 

Jonathan Derrough
+33 (0) 6 84 74 76 03
jonathan.derrough@gmail.com
