### ISSUE TITLE
Help UnitySlippyMap

### ISSUE THREAD

**Issue by nabilfx** [jderrough/UnitySlippyMap#16]
Hi Jonathan, when i load the app with UnitySlippyMap works fine the first time lauched, but then, i load another scene, and then load back again the UnitySlippyMap, and this error appear, (MissingReferenceException: The object of type 'TileBehaviour' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.)

How can i fax that please?

**Comment by jderrough** [comment]
Hi @nabilfx,

Can you tell where the error is happening exactly (script, line number), please? It should be in the stack trace printed in the console.
