### ISSUE TITLE
Can't see markers on the map

### ISSUE THREAD

**Issue by egemenertugrul** [jderrough/UnitySlippyMap#19]
I'm sorry for a newbie question here, I think I couldn't find a way to generate markers on the map. 

I can see that this line should work: `map.CreateMarker<MarkerBehaviour>("test marker - 9 rue Gentil, Lyon", new double[2] { 4.83527, 45.76487 }, markerGO);` but i don't see any markers on the map. 

Also I'm getting the error: 

> DllNotFoundException: sqlite3
> SqliteDatabase.Open (System.String path) (at Assets/UnitySlippyMap/Helpers/SQLite/SqliteDatabase.cs:91)
> UnitySlippyMap.Layers.MBTilesLayerBehaviour.Open () (at Assets/UnitySlippyMap/Layers/MBTilesLayerBehaviour.cs:173)
> UnitySlippyMap.Layers.MBTilesLayerBehaviour.set_Filepath (System.String value) (at Assets/UnitySlippyMap/Layers/MBTilesLayerBehaviour.cs:53)
> TestMap+<Start>c__Iterator0.MoveNext () (at Assets/TestScripts/TestMap.cs:273)
> 

maybe those are related?

**Comment by pirou** [comment]
Hi, you need to add a dll to make it work. I am not sure if all of the errors are related but you should add the sqlite3.dll into the plugins folder to at least get rid of the first one.
If i understood correclty, the MBTiles specification is an efficient format for storing millions of tiles in a single SQLite database. As it is a SQLite database, you need to add a DLL to use it (it's a local one database). 
You need to add the dll corresponding to your architecture of course. (on windows, 32 or 64 bits)

**Comment by jderrough** [comment]
Usually the SQLite3 library is already present on your OS. What OS are running @egemenertugrul?

**Comment by egemenertugrul** [comment]
@pirou Alright I'm going to add the dll file now.

@jderrough I'm currently using Windows 8.1 Pro 64 bit

**Comment by egemenertugrul** [comment]
Adding the corresponding dll file from https://www.sqlite.org/download.html to the Assets/Plugins folder solved it! Thanks for your help, have a nice day!
