### ISSUE TITLE
How to enable caching?

### ISSUE THREAD

**Issue by mittal07abhilash** [jderrough/UnitySlippyMap#22]
The plugin keeps the tiles visible on the screen in cache and no other which makes the navigation experience quite slow.  Is there a way to enable caching for the OSM map in the plugin?

**Comment by ScareCrow95** [comment]
https://imgflip.com/i/19bzb8

**Comment by ravaan** [comment]
Github is not 9Gag, it's for serious development. Please delete the comment.

**Comment by ravaan** [comment]
There are quite a few ways to implement caching, the plugin itself has a small implementation which can easily be turned on  ( did you go through the scripts? ).
You can also implement your own custom caching, which would be most suitable for you. You could go on implementing custom caching by saving the image tile downloaded while making the tile request. 
If all this seems too tough you can go for other slippy map implementation's ( not free ) available on Unity Asset Store. 
Hope this helps!

**Comment by jderrough** [comment]
For the record, UnitySlippyMap already has a cache mechanism to avoid loading the tiles multiple times.

https://github.com/jderrough/UnitySlippyMap/blob/master/Assets/UnitySlippyMap/Map/TileDownloaderBehaviour.cs
