### ISSUE TITLE
Marks not appearing

### ISSUE THREAD

**Issue by kelvindavies11** [jderrough/UnitySlippyMap#23]
Hi team,
Is anyone else having issues with the markers not appearing?  I see there is a todo for the marker layer, but was wondering if the current version works as expected.

Thank you.

Kelvin

**Comment by ScareCrow95** [comment]
Do you get an MBtile layer error as well? Happened with me too , its because generate markers is called after its checking for mbtile layers and for some reason code stops there (some library is missing) since I was not using the Mbtile functionality I just removed that block of the code , or instead just move the marker generation code above the mb tile layer thing.

**Comment by kelvindavies11** [comment]
Brilliant and thank you ScareCrow95, that worked a treat.  Can I ask what you used the slippymap example for?  I am interested in the framework and providing a custom colour scheme to the maps and was wondering if you had any hints?  For example, how can I change the road colour to green.

Thank you.

Kelvin

**Comment by ScareCrow95** [comment]
you're welcome, glad it worked out, I switched to the online map assets though on the unity asset store its a paid plugin with great support, and we are making a location based game which requires a map to be played on , and after lots of googling and hair pulling we finally figured out a way to host our own tile server server AWS and adding a customised style, if you want more details just add me on skype mridul.notmridul

**Comment by ravaan** [comment]
What you are asking in creating a custom Styled Tile Server using  starting by making a style using any one of the opensource tools and adding that to the OpenStreet Data and then adding that to a PostgressSQL Database on you server using Mpanik, Mod Tile and Renderd mainly. This is quite lot of work and there are quite a few logistical as well as documentation problems. 

Logistical Problem : The work is hardware intensive and takes time.

Documentation Problem: The whole process is a bit complex and very badly document online. Many of required tools are not documented at all.

Covering the whole process here won't be possible.

If you have any specific query I would be happy to answer that.
