### ISSUE TITLE
Map on plane

### ISSUE THREAD

**Issue by floriancoding** [jderrough/UnitySlippyMap#24]
Hi,

im pretty new to unity and asking myself if it may be possible to render the map to a simple plane instead of the camera? What i try to achieve basically is:

Rendering the map to a plane, my "game world" so to speak. There were many libraries on the internet, which can render a map with openstreetmaps, but I don't want it to be a real 3D map but a 2D map instead. The problem is, with the camera rendering the map i can't zoom and place 3D objects, like a player model on it.

Any help would be appreciated, just some tips may be enough, as I'm already looking to find the solution, but if it's definitely impossible I wouldn't waste that much time on it and instead search for another solution.

Regards,

Flo

**Comment by rizz360** [comment]
Hey floriancoding!

I am currently looking into this, too. I've achieved a similar effect by applying a RenderTexture to the desired object (in your case a simple plane) and adding a dedicated camera viewing the map.
Have you found a better solution or workaround yourself?

Cheers
Rizz
