### ISSUE TITLE
Web player is deprecated

### ISSUE THREAD

**Issue by tanlah** [jderrough/UnitySlippyMap#26]
Starting with Unity 5.4, Web Player was deprecated https://blogs.unity3d.com/2015/10/08/unity-web-player-roadmap/

References to it should be removed, as I don't think anybody will be using it. Firefox & Chrome have dropped support for NPAPI plugins

**Comment by jderrough** [comment]
Here you go: a7f41168171b2df259a690f1f3117db79619a4d9
