### ISSUE TITLE
Remove .mbtiles binary file from repo

### ISSUE THREAD

**Issue by tanlah** [jderrough/UnitySlippyMap#28]
There's a huge 60mb binary .mbtiles repo at https://github.com/jderrough/UnitySlippyMap/tree/master/Assets/StreamingAssets/MBTiles
It seems to be a cache for Mapbox tiles, it should be generated on runtime as needed, not included

**Comment by jderrough** [comment]
The MBtiles files included in the test project are providing demo data. They should not be included in your own project if you don't need them.
