### ISSUE TITLE
Try setting the starting long lat to 14.4255, 121.0017

### ISSUE THREAD

**Issue by makobec** [jderrough/UnitySlippyMap#34]
The logs says two errors.
ArgumentException: Transformation cannot be computed at the poles.
transform.position assign attempt for '[Map]' is not valid. Input position is { -889.065186, 0.000000, NaN }.

**Comment by jderrough** [comment]
@makobec Longitude should be comprised between -180 and 180, and latitude between -90 and 90. In UnitySlippyMap, coordinates are longitude-first.
