### ISSUE TITLE
Streaming WMS data

### ISSUE THREAD

**Issue by ColivienteR** [jderrough/UnitySlippyMap#6]
The URL used for the WMS tiles seems to no longer be accessible or the 1.1.1 version is no more usable:

ERROR: WMSTileLayer.Update: loader [http://labs.metacarta.com/wms/vmap0?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.1] error: couldn't connect to host()

**Comment by jderrough** [comment]
Fixed with commit 34406341a0e60523908b40314f36e037f601db2d
